services:
  backend:
    build: ./back
    # ports:
    #   - "3001:3001" 
    environment:
      - PORT=3001
      - NODE_ENV=production
    restart: always

  frontend:
    image: nginx:alpine
    volumes:
      - ./nginx-lb.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend-worker
    restart: always

  frontend-worker:
    build:
      context: ./front
      args:
        PUBLIC_API_URL: "https://api.jejamel.me"
    deploy:
      replicas: 3 
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: always
    depends_on:
      - frontend
      - backend
