services:
  backend:
    build: ./back
    # ports:
    #   - "3001:3001" 
    environment:
      - PORT=3001
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: ./front
      args:
        PUBLIC_API_URL: "https://api.jejamel.me"
    restart: always
    depends_on:
      - backend

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: always
    depends_on:
      - frontend
      - backend
